c_stdlib:
- vs
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
docker_image:
- quay.io/condaforge/linux-anvil-x86_64:alma9
go_compiler:
- go-nocgo
target_goexe:
- .exe
target_platform:
- win-64
