[workspace]
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
channels = ["conda-forge"]
name = "rattler-build-parser-tests"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.1,<3.15"
deepdiff = ">=8.6.1,<9"
tomli = ">=2.3.0,<3"
pyyaml = ">=6.0.3,<7"
