channel_targets:
  - conda-forge mpi-external  # [linux]
  - conda-forge main
mpi_type:
  - external  # [linux]
  - conda
libfabric:
  # build against libfabric 1.19
  # for compatibility with ABI 1.6 (libfabric 1.14)
  # this is forward-compatible with libfabric 2.x
  - "1.19"

zip_keys:
  -
    - mpi_type
    - channel_targets
