c_stdlib_version:  # [osx and x86_64]
 - "10.15"         # [osx and x86_64]
MACOSX_SDK_VERSION:    # [osx]
  - "14.5"             # [osx]
c_compiler_version:    # [osx]
  - 21                 # [osx]
cxx_compiler_version:  # [osx]
  - 21                 # [osx]
