# Needed for Metal, the hardware acceleration api for osx
# 15.5 is needed for avoiding bugs like https://github.com/conda-forge/opencv-feedstock/issues/493
MACOSX_SDK_VERSION:  # [osx]
  - 15.5             # [osx]

# Needed to use std::filesystem in osx
c_stdlib_version:  # [osx and x86_64]
  - '10.15'        # [osx and x86_64]

# Use the same version specified in https://github.com/rerun-io/rerun/blob/0.23.1/rust-toolchain#L8
# (or the similar file in the current version)
rust_compiler_version:
  - 1.88.0
